export enum Configuration {
  DB_NAME = 'DB_NAME',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USER = 'DB_USER',
  DB_PASSWORD = 'DB_PASSWORD',
  PORT_SERVER = 'PORT_SERVER',
  LIST_CORS = 'LIST_CORS',
  EXPIRESIN = 'EXPIRESIN',
  MAX_ACTIVE_SESSIONS = 'MAX_ACTIVE_SESSIONS',
  JWT_SECRET = 'JWT_SECRET',
  REFRESH_TOKEN_TTL = 'REFRESH_TOKEN_TTL',
  INIT_USER = 'INIT_USER',
}
